# Generated by Django 4.2.13 on 2024-07-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
